/*
 * Copyright (c) 2018, Tom Leemreize <https://github.com/oplosthee>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package nl.utwente.ing.model;

public class SavingsGoal {

    private Integer id;
    private String name;
    private Integer goal;
    private Integer savePerMonth;
    private Integer minBalanceRequired;
    private Integer balance;

    /**
     * Constructor to create a SavingGoal.
     *
     * @param id SavingGoal id - should be generated by the database and set by Gson.
     * @param name name of the goal, decided by the user.
     * @param goal the balance to reach for this savings goal
     * @param savePerMonth the amount of money to put aside per month
     * @param minBalanceRequired the minimum balance required for the savings to be put aside
     * @param balance the current amount of savings towards this goal
     */
    public SavingsGoal(Integer id, String name, Integer goal, Integer savePerMonth, Integer minBalanceRequired, Integer balance) {
        this.id = id;
        this.name = name;
        this.goal = goal;
        this.savePerMonth = savePerMonth;
        this.minBalanceRequired = minBalanceRequired;
        this.balance = balance;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public Integer getGoal() {
        return goal;
    }

    public Integer getSavePerMonth() {
        return savePerMonth;
    }

    public Integer getMinBalanceRequired() {
        return minBalanceRequired;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}
