/*
 * Copyright (c) 2018, Tom Leemreize <https://github.com/oplosthee>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package nl.utwente.ing.model;

import com.google.gson.annotations.Expose;

import javax.persistence.*;

@Entity
@Table(name = "savingsgoals")
public class SavingsGoal {

    @Id
    @GeneratedValue(generator="sqlite")
    @TableGenerator(name="sqlite", table="sqlite_sequence", pkColumnName="name", valueColumnName="seq", pkColumnValue="savingsgoals")
    @Expose
    private Integer id;

    @Expose
    private String name;

    @Expose
    private Integer goal;

    @Column(name = "monthly")
    @Expose
    private Integer savePerMonth;

    @Column(name = "minbalance")
    @Expose
    private Integer minBalanceRequired;

    @Expose
    private Integer balance;

    private String date;

    @ManyToOne(targetEntity = Session.class)
    @JoinColumn(name = "session_id")
    private Session session;

    public SavingsGoal() {}

    /**
     * Constructor to create a SavingGoal.
     *
     * @param id SavingGoal id - should be generated by the database and set by Gson.
     * @param name name of the goal, decided by the user.
     * @param goal the balance to reach for this savings goal
     * @param savePerMonth the amount of money to put aside per month
     * @param minBalanceRequired the minimum balance required for the savings to be put aside
     * @param balance the current amount of savings towards this goal
     */
    public SavingsGoal(Integer id, String name, Integer goal, Integer savePerMonth, Integer minBalanceRequired, Integer balance) {
        this.id = id;
        this.name = name;
        this.goal = goal;
        this.savePerMonth = savePerMonth;
        this.minBalanceRequired = minBalanceRequired;
        this.balance = balance;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getGoal() {
        return goal;
    }

    public void setGoal(Integer goal) {
        this.goal = goal;
    }

    public Integer getSavePerMonth() {
        return savePerMonth;
    }

    public void setSavePerMonth(Integer savePerMonth) {
        this.savePerMonth = savePerMonth;
    }

    public Integer getMinBalanceRequired() {
        return minBalanceRequired;
    }

    public void setMinBalanceRequired(Integer minBalanceRequired) {
        this.minBalanceRequired = minBalanceRequired;
    }

    public Integer getBalance() {
        return balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public void setSession(Session session) {
        this.session = session;
    }
}
